let playerName = null;
let actions = [];
let inventory = [];
let waterChestItems = ["Water Staff", "Mermaid's Tear", "Aqua Shield", "Tidal Wave Amulet", "Coral Crown", "Siren's Song Scroll"];
let fireChestItems = ["Flaming Sword", "Phoenix Feather", "Dragon's Breath Potion", "Fire Gem", "Lava Boots", "Inferno Cloak"];
let waterChestOpened = false;
let fireChestOpened = false;
// The names of the items in the two lists above were generated by AI.

const buttonSound = new Audio('sound/start-game.mp3')
const forestSound = new Audio('sound/forest.mp3')
const fireSound = new Audio('sound/fire.mp3')
const waterSound = new Audio('sound/atlantis.mp3')
restartGameFlow();
function chest(type) {
    buttonSound.play();
    document.getElementById("restartBtn").disabled = false;
    document.getElementById("backBtn").disabled = false;
    let c1 = document.getElementById("c1");
    let c2 = document.getElementById("c2");
    let chestItemsReceived = [];

    if ((type === "water" && waterChestOpened) || (type === "fire" && fireChestOpened)) {
        c1.disabled = true;
        c1.textContent = "Already opened!";
        area2(inventory,type);
        return;
    }

    c1.addEventListener("click", function () {

        if ((type === "water" && waterChestOpened) || (type === "fire" && fireChestOpened)) {
            return;
        }
        if (type === "water") {
            waterChestOpened = true;
        } else {
            fireChestOpened = true;
        }

        let chestItems = [];
        if (type === "water") {
            chestItems = [...waterChestItems];
        } else {
            chestItems = [...fireChestItems];
        }
        for (let i = 0; i < 3; i++) {
            let randomIndex = Math.floor(Math.random() * chestItems.length);
            let item = chestItems[randomIndex];
            if (i === 2) {
                chestItemsReceived.push("and " + item);
            } else {
                chestItemsReceived.push(item);
            }
            inventory.push(item);
            chestItems.splice(randomIndex, 1);
        }
        let chestName = type.charAt(0).toUpperCase() + type.slice(1);
        actions.push("Opened the " + chestName + " Chest and found " + chestItemsReceived.join(", "));
        document.getElementById("yourActions").textContent = actions.join(", ");
        document.getElementById("storyTxt").textContent =
        "You opened the " + chestName + " Chest and found " + chestItemsReceived.join(", ") + "! Your adventure will continue soon...";
        document.getElementById("inventory").textContent = inventory.join(", ");
        c1.disabled = true;
   
        c1.textContent = "Already opened!";
        c2.textContent = "Continue Your Journey!";
        area2(chestItemsReceived.join(", "));
    });
        c2.addEventListener("click", function () {
        actions.push("Left the Chest Alone");
        document.getElementById("yourActions").textContent = actions.join(", ");
        document.getElementById("storyTxt").textContent = 
        "You decided to leave the chest alone. You go back to the forest.";
        startGameFlow();
    });
}

function stopAllSounds() {
    [buttonSound, fireSound, waterSound, forestSound].forEach(sound => {
        sound.pause();
        sound.currentTime = 0;
    });
}


function setupInitialChoices() {
    let c1 = document.getElementById("c1");
    let c2 = document.getElementById("c2");
    document.getElementById("storyTxt").textContent = "You find yourself in a mysterious forest. Two paths lie ahead. Which way do you go?"

    c1.addEventListener("click", function handleLeft() {
        if (this.textContent === "Go Left") {
            stopAllSounds();
            actions.push("Went Left");
            document.body.style.backgroundImage = "url('image/atlantis.jpg')";
            document.body.style.backgroundImageSize = "100% 100%";

            document.getElementById("storyTxt").textContent = "You entered Atlantis. Oh look, a chest!";

            waterSound.loop = true;
            waterSound.volume = 0.25;
            waterSound.play();

            let c1 = document.getElementById("c1");
            let c2 = document.getElementById("c2");

            c1.replaceWith(c1.cloneNode(true));
            c2.replaceWith(c2.cloneNode(true));
            c1 = document.getElementById("c1");
            c2 = document.getElementById("c2");
            
            //AI helped me with the four lines above so that duplicate event listeners won't be added when the player goes back to the chest after leaving it alone.

            c1.textContent = "Open the Chest";
            c2.textContent = "Leave it Alone";
            
            chest("water");
        }
    });

    c2.addEventListener("click", function handleRight() {
        if (this.textContent === "Go Right") {
            stopAllSounds();
            document.body.style.backgroundImage = "url('image/underworld.jpg')";
            document.body.style.backgroundImageSize = "50% 50%";
            actions.push("Went Right");
            document.getElementById("storyTxt").textContent = "You entered the Underworld. Oh look, a chest!";

            fireSound.loop = true;
            fireSound.volume = 0.5;
            fireSound.play();

            let c1 = document.getElementById("c1");
            let c2 = document.getElementById("c2");

            c1.replaceWith(c1.cloneNode(true));
            c2.replaceWith(c2.cloneNode(true));
            c1 = document.getElementById("c1");
            c2 = document.getElementById("c2");
            //AI helped me with the four lines above so that duplicate event listeners won't be added when the player goes back to the chest after leaving it alone.

            c1.textContent = "Open the Chest";
            c2.textContent = "Leave it Alone";

            chest("fire");
        }
    });
}

function startGameFlow() {
    stopAllSounds();
    forestSound.loop = true;
    forestSound.volume = 0.5;
    forestSound.play();
    document.getElementById("backBtn").disabled = true;
    document.body.style.backgroundImage = "url('image/forest.jpg')"
    document.body.style.backgroundPosition = "0px -100px";
    document.body.style.backgroundImageSize = "100% 100%";
    buttonSound.play();
    let c1 = document.getElementById("c1");
    let c2 = document.getElementById("c2");

    c1.replaceWith(c1.cloneNode(true));
    c2.replaceWith(c2.cloneNode(true));

    c1 = document.getElementById("c1");
    c2 = document.getElementById("c2");
    c1.disabled = false;
    c2.disabled = false;
    c1.textContent = "Go Left";
    c2.textContent = "Go Right";

    document.getElementById("startBtn").disabled = true;

    setupInitialChoices();
    buttonSound.play();
}

function restartGameFlow() {
    stopAllSounds();
    document.getElementById("backBtn").disabled = true;
    document.body.style.backgroundImage = "url('image/forest.jpg')"
    document.body.style.backgroundPosition = "0px 0px";
    document.body.style.backgroundImageSize = "100% 100%";
    buttonSound.play();
    document.getElementById("storyTxt").textContent = "Story text will appear here...";
    document.getElementById("yourActions").textContent = "Your actions will appear here...";
    document.getElementById("inventory").textContent = "Your inventory will appear here...";
    let c1 = document.getElementById("c1");
    let c2 = document.getElementById("c2");

    c1.replaceWith(c1.cloneNode(true));
    c2.replaceWith(c2.cloneNode(true));

    c1 = document.getElementById("c1");
    c2 = document.getElementById("c2");
    c1.disabled = true;
    c2.disabled = true;
    c1.textContent = "Choice 1";
    c2.textContent = "Choice 2";

    document.getElementById("startBtn").disabled = true;
    actions = [];
    inventory = [];

    document.body.style.backgroundImage = "url('image/CYOA-Background.jpg')"
    document.body.style.backgroundSize = "cover";
    document.getElementById("name").value = "";
    document.getElementById("name").disabled = false;
    document.getElementById("nameBtn").disabled = true;
    document.getElementById("restartBtn").disabled = true;
    buttonSound.play();
}


document.getElementById("name").addEventListener("input", function () {
    playerName = this.value.trim();
    document.getElementById("nameBtn").disabled = (playerName === "");
});

document.getElementById("nameBtn").addEventListener("click", function () {
    playerName = playerName.charAt(0).toUpperCase() + playerName.slice(1).toLowerCase();
    document.getElementById("header").textContent = playerName + "'s Adventure";
    document.getElementById("nameBtn").disabled = true;
    document.getElementById("name").disabled = true;
    document.getElementById("startBtn").disabled = false;
    document.getElementById("storyTxt").textContent = "Welcome, " + playerName + "! Click the Start button to begin!";
    buttonSound.play();
});


document.getElementById("startBtn").addEventListener("click", function () {
    startGameFlow();
});

document.getElementById("backBtn").addEventListener("click", function () {
    stopAllSounds();
    forestSound.loop = true;
    forestSound.volume = 0.5;
    forestSound.play();
    document.getElementById("backBtn").disabled = true;
    document.body.style.backgroundImage = "url('image/forest.jpg')"
    document.body.style.backgroundPosition = "0px -100px";
    document.body.style.backgroundImageSize = "100% 100%";
    buttonSound.play();
    let c1 = document.getElementById("c1");
    let c2 = document.getElementById("c2");

    c1.replaceWith(c1.cloneNode(true));
    c2.replaceWith(c2.cloneNode(true));

    c1 = document.getElementById("c1");
    c2 = document.getElementById("c2");
    c1.disabled = false;
    c2.disabled = false;
    c1.textContent = "Go Left";
    c2.textContent = "Go Right";

    document.getElementById("startBtn").disabled = true;

    setupInitialChoices();
});

document.getElementById("restartBtn").addEventListener("click", function () {

    document.getElementById("backBtn").disabled = true;
    restartGameFlow();
});

function area2(items, dragonType) {
    document.getElementById("storyTxt").textContent = "You encounter a fierce " + dragonType +" Dragon! Do you fight it or run away?";
    let c1 = document.getElementById("c1");
    let c2 = document.getElementById("c2");
    c1.textContent = "Fight Him!";
    c2.textContent = "Run Away!";

    c1.addEventListener("click", function () {
        actions.push("You fought the Dragon and won!");
        document.getElementById("yourActions").textContent = actions.join(", ");
        document.getElementById("storyTxt").textContent =
        "You decide to fight the dragon with your " + items + ". After a tough battle, you emerge victorious! You continue your adventure with your new loot.";
        document.getElementById("inventory").textContent = inventory.join(", ");
    });
        c2.addEventListener("click", function () {
        actions.push("Tried to leave but couldn't.");
        document.getElementById("yourActions").textContent = actions.join(", ");
        document.getElementById("storyTxt").textContent = "You tried to run away but the dragon blocked your path!";
    });

}